# Minimal PostgreSQL for IBC-AI Development
# Only provides database - backend runs via minimal_backend virtual environment

services:
  db:
    image: postgres:15
    container_name: ibc_ai_db_minimal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ibc_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: